### ISSUE TITLE
Seeing Python error with script

### ISSUE THREAD

**Issue by castle1126** [cmemery/footprints#2]
Hi, I'm trying to use your code and had an issue.  We are using Footprints 11.6.  I had to make a couple changes to the __init.py__ script for our environment:
1) on line 28 to use the URL we have configured - so the new line is: self.url = "https://{}/MRcgi/MRWebServices.pl.format(webhost)
2) on line 29 I added "verify=False" in the Transport function call, as our system uses self signed certs that fail the requests SSL checks.

When I run the steps you note to just look at a ticket I get the following error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "footprints/__init__.py", line 31, in __init__
    transport=Transport(verify=False,http_auth=HTTPBasicAuth(self.user, self.pword)))
  File "/usr/local/lib/python2.7/dist-packages/zeep/client.py", line 52, in __init__
    self.wsdl = Document(wsdl, self.transport)
  File "/usr/local/lib/python2.7/dist-packages/zeep/wsdl/wsdl.py", line 59, in __init__
    document = self._load_content(location)
  File "/usr/local/lib/python2.7/dist-packages/zeep/wsdl/wsdl.py", line 127, in _load_content
    return load_external(location, self.transport, self.location)
  File "/usr/local/lib/python2.7/dist-packages/zeep/parser.py", line 21, in load_external
    response = transport.load(url)
  File "/usr/local/lib/python2.7/dist-packages/zeep/transports.py", line 41, in load
    response.raise_for_status()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 862, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 411 Client Error: Length Required for url: https://footprints-prod/MRcgi/MRWebServices.pl

I'm not sure if there's a general issue with the script or have my changes to the script caused the issue.  Any insight would be greatly appreciated!

Thanks!
Steve

**Comment by cmemery** [comment]
It sounds like you may be using tag 2.0. Try tag 1.0 for FP 11.6.

**Comment by castle1126** [comment]
Thanks Chris, that did the trick!

Steve
